name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]  # Set the default Python version here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
        sudo apt-get install build-essential
    
    - name: List directory contents  # Add this step to verify the path
      run: ls -la projects

    - name: Install dependencies
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install flake8
        flake8 . || true

    - name: Lint with black
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install black
        black --check . || true

    - name: Check types with mypy
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install mypy
        mypy . || true

    - name: Security check with bandit
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install bandit
        bandit -r . || true

    - name: Test with pytest
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q || true

    - name: Generate coverage report
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install coverage
        coverage run -m pytest --maxfail=1 --disable-warnings -q
        coverage xml

    - name: Build documentation
      working-directory: projects/Calculate_age/docs  # Set the working directory
      run: |
        pip install sphinx
        make html

    - name: Check documentation links
      working-directory: projects/Calculate_age/docs  # Set the working directory
      run: |
        pip install sphinx
        make linkcheck || true

    - name: Static code analysis with pylint
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install pylint
        pylint projects/Calculate_age

    - name: Dependency scanning with safety
      working-directory: projects/Calculate_age  # Set the working directory
      run: |
        pip install safety
        safety check || true
